'use client';
import { useCallback, useEffect, useState } from 'react';
import dynamic from 'next/dynamic';
import { ArrowUpRight, BookOpen, Bot, Check, ChevronRight, CircleHelp, Code2, Command, FlaskConical, FolderGit2, GitBranch, Layers3, Play, Plus, Radio, ShieldCheck, Square, TerminalSquare } from 'lucide-react';
import { isActive, type AgentRecord, type DependencyStatus, type RepositoryInfo } from '@classroom/shared';
const Review = dynamic(() => import('../components/review'), { ssr: false });
const LiveTerminal = dynamic(() => import('../components/terminal'), { ssr: false });
const backend = process.env.NEXT_PUBLIC_BACKEND_URL || 'http://127.0.0.1:4000';
const demoTask = 'Add a friendly exclamation mark to the greeting function.';
export default function Dashboard() {
  const [reviewAgent, setReviewAgent] = useState<AgentRecord | null>(null);
  const [repository, setRepository] = useState<RepositoryInfo | null>(null);
  const [agent, setAgent] = useState<AgentRecord | null>(null);
  const [runner, setRunner] = useState<'demo' | 'codex'>('demo');
  const [task, setTask] = useState(demoTask);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [online, setOnline] = useState(false);
  const [dependencies, setDependencies] = useState<DependencyStatus | null>(null);
  const [now, setNow] = useState(Date.now());
  const refresh = useCallback(async () => { try { const response = await fetch(`${backend}/api/state`); if (!response.ok) throw new Error(); const data = await response.json(); setRepository(data.repository); setOnline(true); setAgent(data.agents[0] ?? null); if (data.repositoryError) setError(data.repositoryError); } catch { setOnline(false); } }, []);
  useEffect(() => { void refresh(); const poll = setInterval(refresh, 3000); const clock = setInterval(() => setNow(Date.now()), 1000); return () => { clearInterval(poll); clearInterval(clock); }; }, [refresh]);
  useEffect(() => { const check = async () => { try { const response = await fetch(`${backend}/api/dependencies`); if (response.ok) setDependencies(await response.json()); } catch { setDependencies(null); } }; void check(); const poll = setInterval(check, 15000); return () => clearInterval(poll); }, []);
  const active = !!agent && isActive(agent.status);
  const launch = async () => { setBusy(true); setError(''); try { const response = await fetch(`${backend}/api/agents`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ runner, task }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setAgent(data.agent); } catch (e) { setError((e as Error).message); await refresh(); } finally { setBusy(false); } };
  const stop = async () => { if (!agent) return; setBusy(true); try { const response = await fetch(`${backend}/api/agents/${agent.id}/stop`, { method: 'POST' }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setAgent(data.agent); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } };
  const elapsed = agent ? Math.max(0, Math.floor(((agent.endedAt ? Date.parse(agent.endedAt) : now) - Date.parse(agent.createdAt)) / 1000)) : 0;
  return <div className="app-shell">
    <aside className="sidebar"><a className="brand" href="/"><span className="brand-icon"><Command size={22}/></span><span>Agent<br/>Classroom<span className="brand-period">.</span></span></a><div className="workspace-label">YOUR WORKSPACE</div><a className="nav-item selected" href="/"><Layers3 size={18}/> Classroom <span>01</span></a><div className="sidebar-note"><div className="note-icon"><BookOpen size={20}/></div><strong>Learn by building.</strong><p>Give an agent a task.<br/>Watch the work happen.</p><span>One step at a time <ArrowUpRight size={14}/></span></div><div className="sidebar-bottom"><span className="avatar">AC</span><div>Local workspace<small><span className="dot green"/> Private to this device</small></div></div></aside>
    <div className="main-wrap"><header className="topbar"><div>Workspace <ChevronRight size={14}/><strong>Classroom</strong></div><span className="local-pill"><span className={`dot ${online ? 'green' : ''}`}/>{online ? 'Local environment' : 'Backend disconnected'}</span></header>
    <main><div className="page-heading"><div className="eyebrow">YOUR CODING LAB</div><div className="heading-row"><div><h1>Welcome to your classroom<span>.</span></h1><p>A little curiosity. A coding agent. Something new to build.</p></div><span className="phase-label">PHASE 03 <span>·</span> QUIZ & MERGE</span></div></div>
    <div className="repository-bar"><span className="repo-icon"><FolderGit2 size={21}/></span><div><small>REPOSITORY</small><strong>{repository?.name || 'Repository unavailable'}</strong></div><span className="repo-divider"/><GitBranch size={16}/><span className="base-branch">{repository?.baseBranch || '—'}</span><span className="base-label">base branch</span><span className="repo-right"><ShieldCheck size={16}/> Separate worktree for every agent</span></div><div className="service-statuses" aria-label="Service status"><span><i className={online ? 'available' : ''}/>Backend {online ? 'connected' : 'disconnected'}</span><span><i className={dependencies?.database.available ? 'available' : ''}/>Database {dependencies?.database.available ? dependencies.database.mode : 'unavailable'}</span><span><i className={agent?.runner === 'demo' ? 'demo' : dependencies?.quizProvider.configured ? 'available' : ''}/>Quiz provider {agent?.runner === 'demo' ? 'demo' : dependencies?.quizProvider.configured ? 'configured' : 'unavailable'}</span></div>
    {!online && <div className="error" role="alert">Cannot reach the backend. Start both services with <code>npm run dev</code>. Reconnecting automatically.</div>}{error && <div className="error" role="alert">{error}</div>}
    <div className="workspace-grid"><section className="launch-panel panel"><div className="section-title"><span className="small-icon"><Plus size={18}/></span><h2>Launch an agent</h2></div><p className="section-description">Choose a runner and give it a place to start.</p><label className="field-label">Runner</label><div className="runner-options"><button className={runner === 'demo' ? 'runner selected-runner' : 'runner'} onClick={() => setRunner('demo')} disabled={active || busy || repository?.demoAllowed === false}><FlaskConical size={19}/><strong>Demo</strong><small>Try it out</small>{runner === 'demo' && <Check size={13} className="runner-check"/>}</button><button className={runner === 'codex' ? 'runner selected-runner' : 'runner'} onClick={() => setRunner('codex')} disabled={active || busy}><Code2 size={19}/><strong>Codex</strong><small>Your local CLI</small>{runner === 'codex' && <Check size={13} className="runner-check"/>}</button></div><div className="runner-description">{runner === 'demo' ? 'A scripted demo. No account or API key needed.' : 'Uses your installed Codex CLI and existing login.'}</div><label className="field-label" htmlFor="task">What should your agent do?</label><textarea id="task" value={task} onChange={e => setTask(e.target.value)} disabled={active || busy} maxLength={8000} placeholder="Describe a small coding task…"/><div className="task-caption">{runner === 'demo' ? 'Demo always runs the sample greeting task.' : 'Be specific. Small tasks are a great start.'}</div><button className="launch-button" onClick={launch} disabled={active || busy || !online || !repository || !task.trim() || (runner === 'demo' && !repository.demoAllowed)}><Play size={15} fill="currentColor"/>{busy && !active ? 'Creating agent…' : 'Launch agent'}<span>↗</span></button><div className="launch-footnote"><GitBranch size={13}/> A fresh branch. Your base stays untouched.</div><div className="how-it-works"><strong>WHAT HAPPENS NEXT</strong><div><span>1</span> An isolated worktree is created</div><div><span>2</span> Your agent starts working</div><div><span>3</span> Follow along in the live terminal</div></div></section>
    <section className="session-column"><div className="agent-panel panel"><div className="agent-top"><span className="agent-icon"><Bot size={25}/></span><div><h2>{agent?.name || 'Your next collaborator'}</h2><p>{agent ? `${agent.runner === 'demo' ? 'Scripted demo' : 'Codex CLI'} · ${agent.task}` : 'Ready when you are. Launch an agent to begin.'}</p></div><span className={`status status-${agent?.status || 'ready'}`}><span className="dot"/>{agent?.status || 'Ready'}</span></div><div className="agent-meta"><div><small><GitBranch size={13}/> BRANCH</small><span title={agent?.branch}>{agent?.branch || 'Created on launch'}</span></div><div><small>ELAPSED</small><span>{String(Math.floor(elapsed / 60)).padStart(2, '0')}:{String(elapsed % 60).padStart(2, '0')}</span></div><button className="stop-button" disabled={!active || agent?.status === 'stopping' || busy} onClick={stop}><Square size={12} fill="currentColor"/>{agent?.status === 'stopping' ? 'Stopping…' : 'Stop agent'}</button></div>{agent && !isActive(agent.status) && agent.worktree && <button className="review-entry" onClick={() => { setReviewAgent(agent); setTimeout(() => document.querySelector('.review-panel')?.scrollIntoView({ behavior: 'smooth' }), 100); }}>Review changes <ArrowUpRight size={14}/></button>}{agent?.error && <div className="agent-error" role="alert">{agent.error}</div>}</div>
    <div className="terminal-panel"><div className="terminal-toolbar"><div><TerminalSquare size={16}/><strong>Live terminal</strong><span className="terminal-tab">{agent?.runner || 'session'}</span></div><span className="terminal-live"><Radio size={13}/>{active ? 'LIVE' : 'PTY'}</span></div>{agent ? <LiveTerminal id={agent.id} backend={backend} onStatus={setAgent}/> : <div className="terminal-empty"><div className="terminal-watermark"><TerminalSquare size={29}/></div><h3>A front-row seat to the process.</h3><p>Your agent’s terminal will appear here.<br/>Watch it work, type a response, and learn along the way.</p><span><span className="prompt-symbol">❯</span><span className="cursor"/></span></div>}<div className="terminal-bottom"><span><span className="dot"/>{agent ? 'Session output retained' : 'Waiting for an agent'}</span><span>xterm.js <span>·</span> interactive terminal</span></div></div>
    <div className="tip"><CircleHelp size={17}/><p><strong>You’re part of the process.</strong> Click inside the terminal to type. In the demo, press Enter when your agent asks to continue.</p></div></section></div>
    {reviewAgent && <Review key={reviewAgent.id} agent={reviewAgent} backend={backend} onClose={() => setReviewAgent(null)}/>}
    <footer><span><ShieldCheck size={14}/> Runs locally. Worktrees separate files; they are not a security sandbox.</span><span>Built for curious minds <span className="footer-star">✳</span></span></footer></main></div>
  </div>;
}
