'use client';
import { useCallback, useEffect, useState } from 'react';
import dynamic from 'next/dynamic';
import { ArrowUpRight, BookOpen, Bot, Check, ChevronRight, CircleHelp, Code2, Command, FlaskConical, FolderGit2, GitBranch, Layers3, Play, Plus, Radio, ShieldCheck, Square, TerminalSquare } from 'lucide-react';
import { isActive, type AgentRecord, type DependencyStatus, type RepositoryInfo } from '@classroom/shared';
import { backendFetch } from '../lib/backend-fetch';
const Review = dynamic(() => import('../components/review'), { ssr: false });
const LiveTerminal = dynamic(() => import('../components/terminal'), { ssr: false });
const backend = process.env.NEXT_PUBLIC_BACKEND_URL || 'http://127.0.0.1:4000';
const backendHost = new URL(backend).hostname;
const localBackend = backendHost === 'localhost' || backendHost === '127.0.0.1' || backendHost === '::1';
const demoTask = 'Add validation that rejects empty task titles and add a test for whitespace-only input.';
type BackendStatus = 'checking' | 'online' | 'offline';
const requestError = (error: unknown) => error instanceof TypeError
  ? 'The request could not reach the backend. Check that the configured backend is running and accessible.'
  : error instanceof Error ? error.message : 'The request failed. Please try again.';
export default function Dashboard() {
  const [reviewAgent, setReviewAgent] = useState<AgentRecord | null>(null);
  const [repository, setRepository] = useState<RepositoryInfo | null>(null);
  const [agent, setAgent] = useState<AgentRecord | null>(null);
  const [runner, setRunner] = useState<'demo' | 'codex'>('demo');
  const [task, setTask] = useState(demoTask);
  const [busy, setBusy] = useState(false);
  const [actionError, setActionError] = useState('');
  const [repositoryError, setRepositoryError] = useState('');
  const [backendStatus, setBackendStatus] = useState<BackendStatus>('checking');
  const [dependencies, setDependencies] = useState<DependencyStatus | null>(null);
  const [dependencyCheckFailed, setDependencyCheckFailed] = useState(false);
  const [now, setNow] = useState(Date.now());
  const refresh = useCallback(async () => { try { const [health, response] = await Promise.all([backendFetch(`${backend}/health`), backendFetch(`${backend}/api/state`)]); if (!health.ok || !response.ok) throw new Error('Backend health check failed.'); const data = await response.json(); setRepository(data.repository); setBackendStatus('online'); setAgent(data.agents[0] ?? null); setRepositoryError(data.repositoryError || ''); setActionError(current => current.startsWith('The request could not reach the backend.') ? '' : current); } catch { setBackendStatus('offline'); } }, []);
  const checkDependencies = useCallback(async () => { try { const response = await backendFetch(`${backend}/api/dependencies`); if (!response.ok) throw new Error(); setDependencies(await response.json()); setDependencyCheckFailed(false); } catch { setDependencies(null); setDependencyCheckFailed(true); } }, []);
  useEffect(() => { void refresh(); const poll = setInterval(refresh, 3000); const clock = setInterval(() => setNow(Date.now()), 1000); return () => { clearInterval(poll); clearInterval(clock); }; }, [refresh]);
  useEffect(() => { void checkDependencies(); const poll = setInterval(checkDependencies, 15000); return () => clearInterval(poll); }, [checkDependencies]);
  const online = backendStatus === 'online';
  const active = !!agent && isActive(agent.status);
  const launch = async () => { setBusy(true); setActionError(''); try { const response = await backendFetch(`${backend}/api/agents`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ runner, task }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setAgent(data.agent); } catch (e) { setActionError(requestError(e)); await refresh(); } finally { setBusy(false); } };
  const stop = async () => { if (!agent) return; setBusy(true); setActionError(''); try { const response = await backendFetch(`${backend}/api/agents/${agent.id}/stop`, { method: 'POST' }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setAgent(data.agent); } catch (e) { setActionError(requestError(e)); await refresh(); } finally { setBusy(false); } };
  const elapsed = agent ? Math.max(0, Math.floor(((agent.endedAt ? Date.parse(agent.endedAt) : now) - Date.parse(agent.createdAt)) / 1000)) : 0;
  return <div className="app-shell">
    <aside className="sidebar"><a className="brand" href="/"><span className="brand-icon"><Command size={22}/></span><span>Agent<br/>Classroom<span className="brand-period">.</span></span></a><div className="workspace-label">YOUR WORKSPACE</div><a className="nav-item selected" href="/"><Layers3 size={18}/> Classroom <span>01</span></a><div className="sidebar-note"><div className="note-icon"><BookOpen size={20}/></div><strong>Learn by building.</strong><p>Give an agent a task.<br/>Watch the work happen.</p><span>One step at a time <ArrowUpRight size={14}/></span></div><div className="sidebar-bottom"><span className="avatar">AC</span><div>{localBackend ? 'Local workspace' : 'Remote workspace'}<small><span className="dot green"/> {localBackend ? 'Private to this device' : backendHost}</small></div></div></aside>
    <div className="main-wrap"><header className="topbar"><div>Workspace <ChevronRight size={14}/><strong>Classroom</strong></div><span className={`local-pill ${backendStatus}`}><span className={`dot ${online ? 'green' : ''}`}/>{backendStatus === 'checking' ? 'Checking backend…' : online ? localBackend ? 'Local environment ready' : 'Remote backend connected' : 'Backend disconnected'}</span></header>
    <main><div className="demo-banner" role="status"><FlaskConical size={15}/><strong>Demo mode</strong><span>Deterministic demo runner. No Codex login or Groq key is required.</span></div><div className="page-heading"><div className="eyebrow">YOUR CODING LAB</div><div className="heading-row"><div><h1>Welcome to your classroom<span>.</span></h1><p>Watch the agent, understand its exact change, then earn the merge.</p></div><span className="phase-label">PHASE 05 <span>·</span> DEMO READY</span></div></div>
    <div className="repository-bar"><span className="repo-icon"><FolderGit2 size={21}/></span><div><small>REPOSITORY</small><strong>{backendStatus === 'checking' ? 'Checking repository…' : repository?.name || 'Repository unavailable'}</strong></div><span className="repo-divider"/><GitBranch size={16}/><span className="base-branch">{repository?.baseBranch || '—'}</span><span className="base-label">base branch</span><span className="repo-right"><ShieldCheck size={16}/> Separate worktree for every agent</span></div><div className="service-statuses" aria-label="System health"><span title="Backend HTTP and state API"><i className={online ? 'available' : backendStatus === 'checking' ? 'checking' : ''}/>Backend: {backendStatus === 'checking' ? 'Checking…' : online ? 'Connected' : 'Unavailable'}</span><span title="Opens when an agent session starts"><i className={online ? 'available' : backendStatus === 'checking' ? 'checking' : ''}/>Terminal: {agent ? 'Session ready' : online ? 'Ready on launch' : 'Unavailable'}</span><span title={dependencies?.database.message}><i className={dependencies?.database.available ? 'available' : !dependencies && !dependencyCheckFailed ? 'checking' : ''}/>Supabase: {!dependencies ? dependencyCheckFailed ? 'Check failed' : 'Checking…' : dependencies.database.mode === 'supabase' ? dependencies.database.available ? 'Connected' : 'Unavailable' : 'Not configured · local ready'}</span><span title={dependencies?.quizProvider.message}><i className={dependencies?.quizProvider.configured ? 'available' : !dependencies && !dependencyCheckFailed ? 'checking' : 'demo'}/>Quiz AI: {!dependencies ? dependencyCheckFailed ? 'Check failed' : 'Checking…' : dependencies.quizProvider.configured ? 'Groq configured' : 'Demo available'}</span><span title={dependencies?.codex?.message}><i className={dependencies?.codex?.available ? 'available' : !dependencies && !dependencyCheckFailed ? 'checking' : ''}/>Codex CLI: {!dependencies ? dependencyCheckFailed ? 'Check failed' : 'Checking…' : dependencies.codex?.available ? 'Available' : 'Not found'}</span></div>
    {backendStatus === 'offline' && <div className="connection-error" role="alert"><div><strong>Cannot reach the backend.</strong><span>{localBackend ? <>Keep <code>npm run dev</code> running in this project.</> : <>Check the backend deployment, access session, and configured URL.</>} The page will reconnect automatically.</span></div><button type="button" onClick={() => { setBackendStatus('checking'); void Promise.all([refresh(), checkDependencies()]); }}>Check again</button></div>}{repositoryError && <div className="error" role="alert">{repositoryError}</div>}{actionError && <div className="error" role="alert">{actionError}</div>}
    <div className="workspace-grid"><section className="launch-panel panel"><div className="section-title"><span className="small-icon"><Plus size={18}/></span><h2>Launch an agent</h2></div><p className="section-description">Choose a runner and give it a place to start.</p><label className="field-label">Runner</label><div className="runner-options"><button className={runner === 'demo' ? 'runner selected-runner' : 'runner'} onClick={() => setRunner('demo')} disabled={active || busy || repository?.demoAllowed === false}><FlaskConical size={19}/><strong>Demo</strong><small>Try it out</small>{runner === 'demo' && <Check size={13} className="runner-check"/>}</button><button className={runner === 'codex' ? 'runner selected-runner' : 'runner'} onClick={() => setRunner('codex')} disabled={active || busy}><Code2 size={19}/><strong>Codex</strong><small>Your local CLI</small>{runner === 'codex' && <Check size={13} className="runner-check"/>}</button></div><div className="runner-description">{runner === 'demo' ? 'A scripted demo. No account or API key needed.' : 'Uses your installed Codex CLI and existing login.'}</div><label className="field-label" htmlFor="task">What should your agent do?</label><textarea id="task" value={task} onChange={e => setTask(e.target.value)} disabled={active || busy} maxLength={8000} placeholder="Describe a small coding task…"/><div className="task-caption">{runner === 'demo' ? 'Demo runs the bundled title-validation task.' : 'Be specific. Small tasks are a great start.'}</div><button className="launch-button" onClick={launch} disabled={active || busy || !online || !repository || !task.trim() || (runner === 'demo' && !repository.demoAllowed)}><Play size={15} fill="currentColor"/>{busy && !active ? 'Creating agent…' : 'Launch agent'}<span>↗</span></button><div className="launch-footnote"><GitBranch size={13}/> A fresh branch. Your base stays untouched.</div><div className="how-it-works"><strong>WHAT HAPPENS NEXT</strong><div><span>1</span> An isolated worktree is created</div><div><span>2</span> Your agent starts working</div><div><span>3</span> Follow along in the live terminal</div></div></section>
    <section className="session-column"><div className="agent-panel panel"><div className="agent-top"><span className="agent-icon"><Bot size={25}/></span><div><h2>{agent?.name || 'Your next collaborator'}</h2><p>{agent ? `${agent.runner === 'demo' ? 'Scripted demo' : 'Codex CLI'} · ${agent.task}` : 'Ready when you are. Launch an agent to begin.'}</p></div><span className={`status status-${agent?.status || 'ready'}`}><span className="dot"/>{agent?.status || 'Ready'}</span></div><div className="agent-meta"><div><small><GitBranch size={13}/> BRANCH</small><span title={agent?.branch}>{agent?.branch || 'Created on launch'}</span></div><div><small>ELAPSED</small><span>{String(Math.floor(elapsed / 60)).padStart(2, '0')}:{String(elapsed % 60).padStart(2, '0')}</span></div><button className="stop-button" disabled={!active || agent?.status === 'stopping' || busy} onClick={stop}><Square size={12} fill="currentColor"/>{agent?.status === 'stopping' ? 'Stopping…' : 'Stop agent'}</button></div>{agent && !isActive(agent.status) && agent.worktree && <button className="review-entry" onClick={() => { setReviewAgent(agent); setTimeout(() => document.querySelector('.review-panel')?.scrollIntoView({ behavior: 'smooth' }), 100); }}>Review changes <ArrowUpRight size={14}/></button>}{agent?.error && <div className="agent-error" role="alert">{agent.error}</div>}</div>
    <div className="terminal-panel"><div className="terminal-toolbar"><div><TerminalSquare size={16}/><strong>Live terminal</strong><span className="terminal-tab">{agent?.runner || 'session'}</span></div><span className="terminal-live"><Radio size={13}/>{active ? 'LIVE' : 'PTY'}</span></div>{agent ? <LiveTerminal id={agent.id} backend={backend} onStatus={setAgent}/> : <div className="terminal-empty"><div className="terminal-watermark"><TerminalSquare size={29}/></div><h3>A front-row seat to the process.</h3><p>Your agent’s terminal will appear here.<br/>Watch it work, type a response, and learn along the way.</p><span><span className="prompt-symbol">❯</span><span className="cursor"/></span></div>}<div className="terminal-bottom"><span><span className="dot"/>{agent ? 'Session output retained' : 'Waiting for an agent'}</span><span>xterm.js <span>·</span> interactive terminal</span></div></div>
    <div className="tip"><CircleHelp size={17}/><p><strong>You’re part of the process.</strong> Click inside the terminal to type. In the demo, press Enter when your agent asks to continue.</p></div></section></div>
    {reviewAgent && <Review key={reviewAgent.id} agent={reviewAgent} backend={backend} onClose={() => setReviewAgent(null)}/>}
    <footer><span><ShieldCheck size={14}/> Worktrees separate files; they are not a security sandbox.</span><span>Built for curious minds <span className="footer-star">✳</span></span></footer></main></div>
  </div>;
}
