import { test, expect } from '@playwright/test';
test('launch, browser terminal input, reconnect replay, completion, stop, and mobile layout', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByRole('button', { name: 'Launch agent' })).toBeEnabled();
  await page.screenshot({ path: 'test-results/dashboard-desktop.png', fullPage: true });
  await page.getByRole('button', { name: 'Launch agent' }).click();
  await expect(page.locator('.status')).toHaveText('running');
  await expect(page.getByRole('button', { name: 'Launch agent' })).toBeDisabled();
  await expect(page.locator('.xterm-screen')).toContainText('Press Enter');
  await page.reload();
  await expect(page.locator('.xterm-screen')).toContainText('Press Enter');
  await page.locator('.xterm-helper-textarea').focus(); await page.keyboard.press('Enter');
  await expect(page.locator('.status')).toHaveText('completed');
  await expect(page.locator('.xterm-screen')).toContainText('Demo complete');
  await page.getByRole('button', { name: 'Launch agent' }).click();
  await expect(page.locator('.status')).toHaveText('running');
  await page.getByRole('button', { name: 'Stop agent' }).click();
  await expect(page.locator('.status')).toHaveText('stopped');
  await expect(page.locator('.xterm-screen')).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByRole('button', { name: 'Launch agent' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/dashboard-mobile.png', fullPage: true });
  expect(errors).toEqual([]);
});

test('review colored changes, write explanations, restore drafts, reject stale versions and preserve typing', async ({ page, request }) => {
  const { writeFile } = await import('node:fs/promises');
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByRole('button', { name: 'Launch agent' })).toBeEnabled();
  await page.getByRole('button', { name: 'Launch agent' }).click();
  await expect(page.locator('.xterm-screen')).toContainText('Press Enter');
  await expect(page.getByRole('button', { name: 'Review changes' })).toHaveCount(0);
  await page.locator('.xterm-helper-textarea').focus(); await page.keyboard.press('Enter');
  await expect(page.locator('.status')).toHaveText('completed');
  await page.getByRole('button', { name: 'Review changes' }).click();
  const review = page.getByRole('region', { name: 'Review and explain' });
  await expect(review.getByText('1 changed file', { exact: true })).toBeVisible();
  await expect(review.locator('.diff-scroll')).toContainText('Hello,');
  await expect(review.getByRole('button', { name: 'Mark explanation complete' })).toBeDisabled();
  const problem = review.getByLabel('1. What problem does this change solve?');
  const solution = review.getByLabel('2. How does the solution work?');
  const edge = review.getByLabel('3. What edge case or failure should be tested?');
  await problem.pressSequentially('Short draft');
  const blocked = await problem.evaluate(el => { const data = new DataTransfer(); data.setData('text/plain', 'pasted answer'); const event = new ClipboardEvent('paste', { clipboardData: data, bubbles: true, cancelable: true }); el.dispatchEvent(event); return event.defaultPrevented; });
  expect(blocked).toBe(true); await expect(problem).toHaveValue('Short draft');
  await expect(review.getByRole('button', { name: 'Mark explanation complete' })).toBeDisabled();
  await expect(review.getByText('Write this explanation in your own words. Pasting is disabled in this activity.')).toBeVisible();
  expect(await problem.evaluate(el => { const event = new DragEvent('drop', { bubbles: true, cancelable: true }); el.dispatchEvent(event); return event.defaultPrevented; })).toBe(true);
  expect(await page.locator('.xterm-helper-textarea').evaluate(el => { const event = new ClipboardEvent('paste', { bubbles: true, cancelable: true }); el.dispatchEvent(event); return event.defaultPrevented; })).toBe(false);
  await review.getByRole('button', { name: 'Save draft', exact: true }).click(); await expect(review.getByText('Draft saved', { exact: true })).toBeVisible();
  await review.getByRole('button', { name: 'Back to classroom' }).click(); await page.getByRole('button', { name: 'Review changes' }).click(); await expect(problem).toHaveValue('Short draft');
  await problem.pressSequentially(' describes the missing punctuation at the end of a greeting.');
  await solution.pressSequentially('The function appends an exclamation mark after the supplied name.');
  await edge.pressSequentially('Check empty names and Unicode names to verify the greeting output.');
  await review.getByRole('button', { name: 'Inline', exact: true }).click(); await expect(review.getByRole('button', { name: 'Inline', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await review.getByRole('button', { name: 'Mark explanation complete' }).click(); await expect(review.locator('.explanation-badge')).toHaveText('Explanation completed');
  await expect(review.locator('.diff-scroll')).toContainText('Before (−) / After (+)');
  await page.screenshot({ path: 'test-results/review-desktop.png', fullPage: true });
  const state = await (await request.get('http://127.0.0.1:4100/api/state', { headers: { Origin: 'http://127.0.0.1:3100' } })).json();
  const agent = state.agents[0];
  await writeFile(`${agent.worktree}/greet.js`, 'export function greet(name) { return `Welcome, ${name}!`; }\n');
  await solution.pressSequentially(' I will inspect the new greeting too.'); const typed = await solution.inputValue();
  await review.getByRole('button', { name: 'Save draft', exact: true }).click(); await expect(review.getByRole('alert')).toContainText('Review changed before submission'); await expect(solution).toHaveValue(typed);
  await review.getByRole('button', { name: 'Refresh changes' }).click(); await expect(review.locator('.diff-scroll')).toContainText('Welcome,'); await expect(solution).toHaveValue(typed); await expect(review.locator('.explanation-badge')).not.toHaveText('Explanation completed');
  await review.getByRole('button', { name: 'Mark explanation complete' }).click(); await expect(review.locator('.explanation-badge')).toHaveText('Explanation completed');
  await page.reload(); await page.getByRole('button', { name: 'Review changes' }).click(); await expect(solution).toHaveValue(typed); await expect(review.locator('.explanation-badge')).toHaveText('Explanation completed');
  await page.setViewportSize({ width: 390, height: 844 }); await expect(review.getByRole('button', { name: 'Inline', exact: true })).toHaveAttribute('aria-pressed', 'true');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await expect(review.locator('.diff-scroll')).toContainText('Welcome,');
  await expect(review.locator('.diff-scroll')).toContainText('Before (−) / After (+)');
  await page.screenshot({ path: 'test-results/review-mobile.png', fullPage: true });
  expect(errors).toEqual([]);
});
