import { test, expect } from '@playwright/test';
test('launch, browser terminal input, reconnect replay, completion, stop, and mobile layout', async ({ page }) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByRole('button', { name: 'Launch agent' })).toBeEnabled();
  await page.screenshot({ path: 'test-results/dashboard-desktop.png', fullPage: true });
  let launched = page.waitForResponse(response => response.url().endsWith('/api/agents') && response.request().method() === 'POST');
  await page.getByRole('button', { name: 'Launch agent' }).click(); await launched;
  await expect(page.locator('.status')).toHaveText('running');
  await expect(page.getByRole('button', { name: 'Launch agent' })).toBeDisabled();
  await expect(page.locator('.xterm-screen')).toContainText('Press Enter');
  await page.reload();
  await expect(page.locator('.xterm-screen')).toContainText('Press Enter');
  await page.locator('.xterm-helper-textarea').focus(); await page.keyboard.press('Enter');
  await expect(page.locator('.status')).toHaveText('completed');
  await expect(page.locator('.xterm-screen')).toContainText('Demo complete');
  launched = page.waitForResponse(response => response.url().endsWith('/api/agents') && response.request().method() === 'POST');
  await page.getByRole('button', { name: 'Launch agent' }).click(); await launched;
  await expect(page.locator('.status')).toHaveText('running');
  await page.getByRole('button', { name: 'Stop agent' }).click();
  await expect(page.locator('.status')).toHaveText('stopped');
  await expect(page.locator('.xterm-screen')).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByRole('button', { name: 'Launch agent' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/dashboard-mobile.png', fullPage: true });
  expect(errors).toEqual([]);
});

test('review colored changes, write explanations, restore drafts, reject stale versions and preserve typing', async ({ page, request }) => {
  const { writeFile, mkdir } = await import('node:fs/promises');
  await mkdir('docs/demo/screenshots', { recursive: true });
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByRole('button', { name: 'Launch agent' })).toBeEnabled();
  await page.screenshot({ path: 'docs/demo/screenshots/01-dashboard.png', fullPage: true });
  const launched = page.waitForResponse(response => response.url().endsWith('/api/agents') && response.request().method() === 'POST');
  await page.getByRole('button', { name: 'Launch agent' }).click(); await launched;
  await expect(page.locator('.xterm-screen')).toContainText('Press Enter');
  await page.screenshot({ path: 'docs/demo/screenshots/02-live-terminal.png', fullPage: true });
  await expect(page.getByRole('button', { name: 'Review changes' })).toHaveCount(0);
  await page.locator('.xterm-helper-textarea').focus(); await page.keyboard.press('Enter');
  await expect(page.locator('.status')).toHaveText('completed');
  await page.getByRole('button', { name: 'Review changes' }).click();
  const review = page.getByRole('region', { name: 'Review and explain' });
  await expect(review.getByText('2 changed files', { exact: true })).toBeVisible();
  await expect(review.locator('.diff-scroll')).toContainText('title.trim');
  await expect(review.getByRole('button', { name: 'Mark explanation complete' })).toBeDisabled();
  const problem = review.getByLabel('1. What problem does this change solve?');
  const solution = review.getByLabel('2. How does the solution work?');
  const edge = review.getByLabel('3. What edge case or failure should be tested?');
  const explanationForm = review.locator('.explanation-form');
  await problem.pressSequentially('Short draft');
  const blocked = await problem.evaluate(el => { const data = new DataTransfer(); data.setData('text/plain', 'pasted answer'); const event = new ClipboardEvent('paste', { clipboardData: data, bubbles: true, cancelable: true }); el.dispatchEvent(event); return event.defaultPrevented; });
  expect(blocked).toBe(true); await expect(problem).toHaveValue('Short draft');
  await expect(review.getByRole('button', { name: 'Mark explanation complete' })).toBeDisabled();
  await expect(review.getByText('Write this explanation in your own words. Pasting is disabled in this activity.')).toBeVisible();
  expect(await problem.evaluate(el => { const event = new DragEvent('drop', { bubbles: true, cancelable: true }); el.dispatchEvent(event); return event.defaultPrevented; })).toBe(true);
  expect(await page.locator('.xterm-helper-textarea').evaluate(el => { const event = new ClipboardEvent('paste', { bubbles: true, cancelable: true }); el.dispatchEvent(event); return event.defaultPrevented; })).toBe(false);
  await explanationForm.getByRole('button', { name: 'Save draft', exact: true }).click(); await expect(review.getByText('Draft saved', { exact: true })).toBeVisible();
  await review.getByRole('button', { name: 'Back to classroom' }).click(); await page.getByRole('button', { name: 'Review changes' }).click(); await expect(problem).toHaveValue('Short draft');
  await problem.pressSequentially(' describes how blank task titles previously created invalid tasks.');
  await solution.pressSequentially('The guard trims the title for its length check and throws for blank input.');
  await edge.pressSequentially('Check a whitespace-only title and confirm that a TypeError is thrown.');
  await review.getByRole('button', { name: 'Inline', exact: true }).click(); await expect(review.getByRole('button', { name: 'Inline', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await review.getByRole('button', { name: 'Mark explanation complete' }).click(); await expect(review.locator('.explanation-badge')).toHaveText('Explanation completed');
  await expect(review.locator('.diff-scroll')).toContainText('Before (−) / After (+)');
  await page.screenshot({ path: 'docs/demo/screenshots/03-review-and-explain.png', fullPage: true });
  await page.screenshot({ path: 'test-results/review-desktop.png', fullPage: true });
  const state = await (await request.get('http://127.0.0.1:4100/api/state', { headers: { Origin: 'http://127.0.0.1:3100' } })).json();
  const agent = state.agents[0];
  await writeFile(`${agent.worktree}/task.js`, "export function createTask(title) {\n  if (typeof title !== 'string' || title.trim().length === 0) throw new TypeError('A visible task title is required.');\n  return { title };\n}\n");
  await solution.pressSequentially(' I will inspect the updated validation message too.'); const typed = await solution.inputValue();
  await explanationForm.getByRole('button', { name: 'Save draft', exact: true }).click(); await expect(review.getByRole('alert')).toContainText('Review changed before submission'); await expect(solution).toHaveValue(typed);
  await review.getByRole('button', { name: 'Refresh changes' }).click(); await expect(review.locator('.diff-scroll')).toContainText('A visible task title is required.'); await expect(solution).toHaveValue(typed); await expect(review.locator('.explanation-badge')).not.toHaveText('Explanation completed');
  await review.getByRole('button', { name: 'Mark explanation complete' }).click(); await expect(review.locator('.explanation-badge')).toHaveText('Explanation completed');
  const quizResponse = page.waitForResponse(response => response.url().endsWith(`/api/agents/${agent.id}/quiz`) && response.request().method() === 'POST');
  await review.getByRole('button', { name: 'Create Demo quiz' }).click(); const quizPayload = await (await quizResponse).json(); expect(JSON.stringify(quizPayload)).not.toContain('correctOptionId'); expect(JSON.stringify(quizPayload)).not.toContain('The returned greeting now');
  await review.getByLabel('It trims every stored title.').check(); await review.getByLabel('So valid titles are stored without spaces.').check(); await review.getByLabel('A disconnected database.').check();
  const firstAttempt = page.waitForResponse(response => response.url().endsWith(`/api/agents/${agent.id}/quiz/attempts`) && response.request().method() === 'POST');
  await review.getByRole('button', { name: 'Submit answers' }).click(); await firstAttempt; await expect(review.getByText('Score: 0/3')).toBeVisible(); await expect(review.getByText('3/3 is required to pass.')).toBeVisible();
  await page.screenshot({ path: 'docs/demo/screenshots/04-quiz-retry.png', fullPage: true });
  await review.getByRole('button', { name: 'Retry quiz' }).click(); await review.getByLabel('It rejects empty and whitespace-only task titles.').check(); await review.getByLabel('So a title made only of whitespace is treated as empty.').check(); await review.getByLabel('A title containing only spaces.').check();
  const passingAttempt = page.waitForResponse(response => response.url().endsWith(`/api/agents/${agent.id}/quiz/attempts`) && response.request().method() === 'POST');
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await review.getByRole('button', { name: 'Submit answers' }).click(); await passingAttempt; await expect(review.getByText('Score: 3/3')).toBeVisible(); await expect(review.getByText('Passed', { exact: true })).toBeVisible();
  await expect(page.locator('body > canvas')).toHaveCount(0);
  const diagramResponse = page.waitForResponse(response => response.url().endsWith(`/api/agents/${agent.id}/diagram`) && response.request().method() === 'POST');
  await review.getByRole('button', { name: 'Build Demo flowchart' }).click(); await diagramResponse;
  await expect(review.getByRole('img', { name: 'Task title validation flow' })).toBeVisible();
  await expect(review.getByText('Whitespace-only regression test')).toBeVisible();
  await expect(review.locator('img[src*="mermaid.ink"]')).toHaveCount(0);
  await page.screenshot({ path: 'docs/demo/screenshots/05-drawing-unlocked.png', fullPage: true });
  const drawing = review.getByRole('region', { name: 'Draw the solution' });
  await drawing.getByLabel('Drawing title').fill('Task title validation flow');
  await drawing.getByLabel('What does your drawing show?').fill('The title enters the validation guard, follows the valid or blank path, and shows the TypeError edge case.');
  const surface = drawing.locator('.canvas-wrap svg'); const box = await surface.boundingBox(); expect(box).not.toBeNull();
  await page.mouse.move(box!.x + 80, box!.y + 90); await page.mouse.down(); await page.mouse.move(box!.x + 260, box!.y + 190, { steps: 8 }); await page.mouse.up();
  let drawingSave = page.waitForResponse(response => response.url().endsWith(`/api/agents/${agent.id}/drawing`) && response.request().method() === 'PUT'); await drawing.getByRole('button', { name: 'Save draft' }).click(); let drawingPayload = await (await drawingSave).json(); expect(drawingPayload.drawing.paths.length).toBeGreaterThan(0);
  await drawing.getByRole('button', { name: 'Undo last drawing action' }).click(); drawingSave = page.waitForResponse(response => response.url().endsWith(`/api/agents/${agent.id}/drawing`) && response.request().method() === 'PUT'); await drawing.getByRole('button', { name: 'Save draft' }).click(); drawingPayload = await (await drawingSave).json(); expect(drawingPayload.drawing.paths).toHaveLength(0);
  await drawing.getByRole('button', { name: 'Redo drawing action' }).click(); drawingSave = page.waitForResponse(response => response.url().endsWith(`/api/agents/${agent.id}/drawing`) && response.request().method() === 'PUT'); await drawing.getByRole('button', { name: 'Save draft' }).click(); drawingPayload = await (await drawingSave).json(); expect(drawingPayload.drawing.paths.length).toBeGreaterThan(0);
  await drawing.getByRole('button', { name: 'Eraser tool' }).click(); await page.mouse.move(box!.x + 150, box!.y + 130); await page.mouse.down(); await page.mouse.move(box!.x + 190, box!.y + 160, { steps: 4 }); await page.mouse.up(); drawingSave = page.waitForResponse(response => response.url().endsWith(`/api/agents/${agent.id}/drawing`) && response.request().method() === 'PUT'); await drawing.getByRole('button', { name: 'Save draft' }).click(); drawingPayload = await (await drawingSave).json(); expect(drawingPayload.drawing.paths.some((item: { drawMode: boolean }) => !item.drawMode)).toBe(true);
  await drawing.getByRole('button', { name: 'Clear drawing canvas' }).click(); drawingSave = page.waitForResponse(response => response.url().endsWith(`/api/agents/${agent.id}/drawing`) && response.request().method() === 'PUT'); await drawing.getByRole('button', { name: 'Save draft' }).click(); drawingPayload = await (await drawingSave).json(); expect(drawingPayload.drawing.paths).toHaveLength(0);
  await drawing.getByRole('button', { name: 'Undo last drawing action' }).click(); drawingSave = page.waitForResponse(response => response.url().endsWith(`/api/agents/${agent.id}/drawing`) && response.request().method() === 'PUT'); await drawing.getByRole('button', { name: 'Save draft' }).click(); drawingPayload = await (await drawingSave).json(); expect(drawingPayload.drawing.paths.length).toBeGreaterThan(0);
  const download = page.waitForEvent('download'); await drawing.getByRole('button', { name: 'Export PNG' }).click(); expect((await download).suggestedFilename()).toBe('task-title-validation-flow.png');
  for (const label of ['My drawing shows the input or starting point.', 'My drawing shows a condition or decision.', 'My drawing shows the result or output.', 'My drawing includes an error or edge-case path.']) await drawing.getByLabel(label).check();
  const completedDrawing = page.waitForResponse(response => response.url().endsWith(`/api/agents/${agent.id}/drawing/complete`) && response.request().method() === 'POST'); await drawing.getByRole('button', { name: 'Mark drawing complete' }).click(); const completedPayload = await (await completedDrawing).json(); expect(completedPayload.drawing.status).toBe('completed'); await expect(drawing.getByText('Completed', { exact: true })).toBeVisible(); await expect(drawing.getByRole('img', { name: /Exported preview/ })).toBeVisible();
  await expect(review.getByText('Learning score: 80/100')).toBeVisible(); await expect(review.getByText('Drawing completion:')).toContainText('10/10'); await expect(review.getByText(/Reviewer mode is disabled by default/)).toBeVisible();
  await expect(review.getByRole('button', { name: 'Merge reviewed changes' })).toBeEnabled(); const mergeResponse = page.waitForResponse(response => response.url().endsWith(`/api/agents/${agent.id}/merge`) && response.request().method() === 'POST', { timeout: 60_000 }); await review.getByRole('button', { name: 'Merge reviewed changes' }).click(); await mergeResponse; await expect(review.getByText('Merged successfully')).toBeVisible(); await expect(review.getByRole('button', { name: 'Already merged' })).toBeDisabled();
  await expect(review.getByText('Learning score: 90/100')).toBeVisible();
  await page.screenshot({ path: 'docs/demo/screenshots/06-merge-success.png', fullPage: true });
  await page.reload(); await page.getByRole('button', { name: 'Review changes' }).click(); await expect(solution).toHaveValue(typed); await expect(review.locator('.explanation-badge')).toHaveText('Explanation completed');
  await page.setViewportSize({ width: 390, height: 844 }); await expect(review.getByRole('button', { name: 'Inline', exact: true })).toHaveAttribute('aria-pressed', 'true');
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await expect(review.locator('.diff-scroll')).toContainText('A visible task title is required.');
  await expect(review.locator('.diff-scroll')).toContainText('Before (−) / After (+)');
  await page.screenshot({ path: 'test-results/review-mobile.png', fullPage: true });
  expect(errors).toEqual([]);
});
