import { fileURLToPath } from 'node:url';
import path from 'node:path';
import dotenv from 'dotenv';
import { AgentManager } from './agent-manager.js';
import { createApp } from './server.js';
import { createLearningStore } from './learning-store.js';
import { GroqQuizProvider } from './quiz-service.js';
const root = fileURLToPath(new URL('../../../', import.meta.url));
dotenv.config({ path: path.join(root, '.env') });
const demoRepo = path.join(root, '.runtime/demo-repo');
const dataRoot = path.resolve(root, process.env.DATA_ROOT || '.runtime/data');
const store = createLearningStore({ mode: process.env.STORAGE_MODE, directory: dataRoot, supabaseUrl: process.env.SUPABASE_URL, supabaseSecretKey: process.env.SUPABASE_SECRET_KEY });
await store.init();
const manager = new AgentManager({ dataRoot, repo: path.resolve(root, process.env.TARGET_REPO || demoRepo), demoRepo, worktreeRoot: path.resolve(root, process.env.WORKTREE_ROOT || '.runtime/worktrees'), demoScript: path.join(root, 'scripts/demo-runner.mjs'), codexExecutable: process.env.CODEX_EXECUTABLE || 'codex' }, undefined, record => store.saveRun(record));
manager.restore(await store.listRuns());
const groqProvider = process.env.GROQ_API_KEY && process.env.GROQ_MODEL ? new GroqQuizProvider(process.env.GROQ_API_KEY, process.env.GROQ_MODEL) : undefined;
const validationArgs = process.env.MERGE_VALIDATION_ARGS_JSON ? JSON.parse(process.env.MERGE_VALIDATION_ARGS_JSON) : undefined;
if (validationArgs && (!Array.isArray(validationArgs) || validationArgs.some(value => typeof value !== 'string'))) throw new Error('MERGE_VALIDATION_ARGS_JSON must be a JSON array of strings.');
const origins = (process.env.ALLOWED_ORIGINS || 'http://127.0.0.1:3000,http://localhost:3000').split(',').map(value => value.trim()).filter(Boolean).map(value => {
  const url = new URL(value); if (!['http:', 'https:'].includes(url.protocol) || url.origin !== value) throw new Error(`ALLOWED_ORIGINS contains an invalid bare origin: ${value}`); return url.origin;
});
if (!origins.length) throw new Error('ALLOWED_ORIGINS must contain at least one exact frontend origin.');
if (process.env.NODE_ENV === 'production' && origins.some(origin => !origin.startsWith('https://') && !/^http:\/\/(?:127\.0\.0\.1|localhost)(?::\d+)?$/.test(origin))) throw new Error('Production ALLOWED_ORIGINS must use HTTPS except for explicit loopback development origins.');
const app = await createApp(manager, origins, { store, groqProvider, validationExecutable: process.env.MERGE_VALIDATION_EXECUTABLE, validationArgs, reviewerMode: process.env.ENABLE_DEMO_REVIEWER_MODE === 'true' });
const port = Number(process.env.PORT || 4000);
const host = process.env.HOST || '127.0.0.1';
if (!Number.isInteger(port) || port < 1 || port > 65535) throw new Error('PORT must be an integer from 1 to 65535.');
app.server.on('error', error => { console.error('Agent Classroom backend failed:', error); process.exitCode = 1; });
app.server.listen(port, host, () => console.log(`Agent Classroom backend listening on http://${host}:${port}`));
let closing = false;
for (const signal of ['SIGINT','SIGTERM'] as const) process.on(signal, () => { if (closing) return; closing = true; void app.close().then(() => process.exit(0)); });
