import { fileURLToPath } from 'node:url';
import path from 'node:path';
import dotenv from 'dotenv';
import { AgentManager } from './agent-manager.js';
import { createApp } from './server.js';
import { createLearningStore } from './learning-store.js';
import { GroqQuizProvider } from './quiz-service.js';
const root = fileURLToPath(new URL('../../../', import.meta.url));
dotenv.config({ path: path.join(root, '.env') });
const demoRepo = path.join(root, '.runtime/demo-repo');
const dataRoot = path.resolve(root, process.env.DATA_ROOT || '.runtime/data');
const store = createLearningStore({ mode: process.env.STORAGE_MODE, directory: dataRoot, supabaseUrl: process.env.SUPABASE_URL, supabaseSecretKey: process.env.SUPABASE_SECRET_KEY });
await store.init();
const manager = new AgentManager({ dataRoot, repo: path.resolve(root, process.env.TARGET_REPO || demoRepo), demoRepo, worktreeRoot: path.resolve(root, process.env.WORKTREE_ROOT || '.runtime/worktrees'), demoScript: path.join(root, 'scripts/demo-runner.mjs'), codexExecutable: process.env.CODEX_EXECUTABLE || 'codex' }, undefined, record => store.saveRun(record));
manager.restore(await store.listRuns());
const groqProvider = process.env.GROQ_API_KEY && process.env.GROQ_MODEL ? new GroqQuizProvider(process.env.GROQ_API_KEY, process.env.GROQ_MODEL) : undefined;
const validationArgs = process.env.MERGE_VALIDATION_ARGS_JSON ? JSON.parse(process.env.MERGE_VALIDATION_ARGS_JSON) : undefined;
if (validationArgs && (!Array.isArray(validationArgs) || validationArgs.some(value => typeof value !== 'string'))) throw new Error('MERGE_VALIDATION_ARGS_JSON must be a JSON array of strings.');
const app = await createApp(manager, (process.env.ALLOWED_ORIGINS || 'http://127.0.0.1:3000,http://localhost:3000').split(',').map(s => s.trim()), { store, groqProvider, validationExecutable: process.env.MERGE_VALIDATION_EXECUTABLE, validationArgs, reviewerMode: process.env.ENABLE_DEMO_REVIEWER_MODE === 'true' });
const port = Number(process.env.PORT || 4000);
app.server.listen(port, '127.0.0.1', () => console.log(`Agent Classroom backend: http://127.0.0.1:${port}`));
let closing = false;
for (const signal of ['SIGINT','SIGTERM'] as const) process.on(signal, () => { if (closing) return; closing = true; void app.close().then(() => process.exit(0)); });
