import { isActive, explanationSchema, explanationComplete, EXPLANATION_MIN, type AgentRecord, type ExplanationInput, type ReviewSnapshot } from '@classroom/shared';
import { collectReview, ReviewError, type CollectedReview } from './review-git.js';
import type { LearningStore } from './learning-store.js';
export class ReviewService {
  private snapshots = new Map<string, CollectedReview & { createdAt: string }>();
  private queues = new Map<string, Promise<unknown>>();
  constructor(private getAgent: (id: string) => AgentRecord, readonly store: LearningStore) {}
  private agent(id: string) { const agent = this.getAgent(id); if (isActive(agent.status)) throw new ReviewError('Agent is still running or stopping. Wait for its process to exit before reviewing.', 409); return agent; }
  private async locked<T>(id: string, action: () => Promise<T>): Promise<T> { const previous = this.queues.get(id) ?? Promise.resolve(); const next = previous.catch(() => {}).then(action); this.queues.set(id, next); try { return await next; } finally { if (this.queues.get(id) === next) this.queues.delete(id); } }
  private async capture(id: string) { const collected = await collectReview(this.agent(id)); const old = this.snapshots.get(id); if (old?.version === collected.version) return old; const snapshot = { ...collected, createdAt: new Date().toISOString() }; this.snapshots.set(id, snapshot); await this.store.saveReview({ agentId: id, version: snapshot.version, createdAt: snapshot.createdAt, files: snapshot.files, additions: snapshot.additions, deletions: snapshot.deletions, canComplete: snapshot.canComplete }); while (this.snapshots.size > 25) this.snapshots.delete(this.snapshots.keys().next().value!); return snapshot; }
  async review(id: string, refresh = false): Promise<ReviewSnapshot> { return this.locked(id, async () => { this.agent(id); const snapshot = !refresh && this.snapshots.get(id) || await this.capture(id); const explanation = await this.store.getExplanation(id, snapshot.version); const latest = await this.store.latestExplanation(id); return { agentId: id, version: snapshot.version, createdAt: snapshot.createdAt, files: snapshot.files, additions: snapshot.additions, deletions: snapshot.deletions, canComplete: snapshot.canComplete, explanation, previousExplanation: latest?.version !== snapshot.version ? latest : null, outdated: !!latest && latest.version !== snapshot.version }; }); }
  file(id: string, version: string, fileId: string) { this.agent(id); const snapshot = this.snapshots.get(id); if (!snapshot || snapshot.version !== version) throw new ReviewError('Review version changed. Refresh changes to load its files.', 409); const file = snapshot.files.find(f => f.id === fileId); if (!file) throw new ReviewError('File does not belong to this review.', 404); const content = snapshot.content.get(fileId); if (!content) throw new ReviewError(file.reason || 'File content is unavailable.'); return { version, fileId, ...content }; }
  async explanation(id: string, version: string) { this.agent(id); if (this.snapshots.get(id)?.version !== version) throw new ReviewError('Review version changed. Refresh changes.', 409); return this.store.getExplanation(id, version); }
  async save(id: string, data: ExplanationInput) { return this.locked(id, async () => {
    const parsed = explanationSchema.safeParse(data); if (!parsed.success) throw new ReviewError('Invalid explanation: version, three plain-text answers, and draft/complete intent are required. Each answer is limited to 6,000 characters.');
    const input = parsed.data; const snapshot = await this.capture(id);
    if (snapshot.version !== input.version) throw new ReviewError('Review changed before submission. Your writing is preserved. Refresh changes and review the new version before saving.', 409);
    if (input.intent === 'complete') { if (!snapshot.canComplete) throw new ReviewError('Explanation cannot be completed: no changes or unsupported/limited files remain.'); if (!explanationComplete(input.answers)) throw new ReviewError(`Each answer needs at least ${EXPLANATION_MIN} non-whitespace characters. This checks completeness, not understanding.`); }
    const now = new Date().toISOString(); return this.store.saveExplanation({ agentId: id, version: input.version, answers: input.answers, status: input.intent === 'complete' ? 'completed' : 'draft', updatedAt: now, ...(input.intent === 'complete' ? { completedAt: now } : {}) });
  }); }
  async currentSnapshot(id: string) { return this.locked(id, () => this.capture(id)); }
  /** Phase 3 prerequisite only; this is not an understanding, quiz, or merge verdict. */
  async isExplanationCompleteForCurrentReview(id: string) { return this.locked(id, async () => { const snapshot = await this.capture(id); const explanation = await this.store.getExplanation(id, snapshot.version); return { version: snapshot.version, complete: snapshot.canComplete && explanation?.status === 'completed' && explanationComplete(explanation.answers) }; }); }
}
