'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import { ReactSketchCanvas, type CanvasPath, type ReactSketchCanvasRef } from 'react-sketch-canvas';
import confetti from 'canvas-confetti';
import { Award, Download, Eraser, Pencil, Redo2, RotateCcw, Save, Sparkles, Trash2, Undo2 } from 'lucide-react';
import { DRAWING_CAPTION_MAX, DRAWING_CAPTION_MIN, DRAWING_TITLE_MAX, badgeKeys, nonWhitespaceLength, type BadgeKey, type DrawingChecklist, type DrawingGuide, type DrawingRecord, type ReviewerMark, type ScoreSummary } from '@classroom/shared';
import { backendFetch } from '../lib/backend-fetch';

const emptyChecklist: DrawingChecklist = { input: false, condition: false, result: false, edgeCase: false };
const badgeLabels: Record<BadgeKey, string> = { code_reader: 'Code Reader', quiz_master: 'Quiz Master', visual_thinker: 'Visual Thinker', safe_merger: 'Safe Merger', full_journey: 'Full Journey' };
const guideLabels: Record<DrawingGuide, string> = { blank: 'Blank', flowchart: 'Flowchart', 'before-after': 'Before and after', 'input-condition-result': 'Input → condition → result' };
const rubricLabels = { relationship: 'Relationship to the reviewed code', flow: 'Clarity of the control or data flow', condition: 'Correct representation of the main condition', edgeCase: 'Inclusion of an error or edge case' } as const;

async function api<T>(url: string, init?: RequestInit): Promise<T> { const response = await backendFetch(url, init); const data = await response.json(); if (!response.ok) throw Object.assign(new Error(data.error || 'Request failed.'), { code: data.code, details: data.details }); return data; }
function celebrate() { if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return; void confetti({ particleCount: 60, spread: 55, origin: { y: .75 }, disableForReducedMotion: true, scalar: .8, ticks: 130 }); }
function guideImage(guide: DrawingGuide) {
  if (guide === 'blank') return '';
  const common = 'fill="none" stroke="#cbd5e1" stroke-width="2" stroke-dasharray="7 7"';
  const shapes = guide === 'flowchart' ? `<rect x="70" y="190" width="180" height="90" rx="12" ${common}/><path d="M250 235h120" ${common}/><path d="m350 220 20 15-20 15" ${common}/><polygon points="470,160 590,235 470,310 350,235" ${common}/><path d="M590 235h120" ${common}/><rect x="710" y="190" width="140" height="90" rx="12" ${common}/><text x="160" y="245">START</text><text x="470" y="240">DECISION</text><text x="780" y="245">RESULT</text>` : guide === 'before-after' ? `<rect x="60" y="70" width="350" height="380" rx="16" ${common}/><rect x="490" y="70" width="350" height="380" rx="16" ${common}/><path d="M410 260h80" ${common}/><text x="235" y="115">BEFORE</text><text x="665" y="115">AFTER</text>` : `<rect x="35" y="180" width="210" height="120" rx="16" ${common}/><polygon points="450,155 570,240 450,325 330,240" ${common}/><rect x="655" y="180" width="210" height="120" rx="16" ${common}/><path d="M245 240h85M570 240h85" ${common}/><text x="140" y="245">INPUT</text><text x="450" y="245">CONDITION</text><text x="760" y="245">RESULT</text>`;
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="900" height="520" viewBox="0 0 900 520"><rect width="900" height="520" fill="#fffdf8"/><g font-family="system-ui" font-size="15" text-anchor="middle" fill="#64748b">${shapes}</g></svg>`;
  return `data:image/svg+xml,${encodeURIComponent(svg)}`;
}

export default function DrawingScore({ agentId, backend, version, quizPassed, achievementTick }: { agentId: string; backend: string; version: string; quizPassed: boolean; achievementTick: number }) {
  const canvas = useRef<ReactSketchCanvasRef>(null); const completionKey = useRef<string | null>(null); const reviewerKey = useRef<string | null>(null); const endpoint = `${backend}/api/agents/${agentId}`;
  const [drawing, setDrawing] = useState<DrawingRecord | null>(null); const [previous, setPrevious] = useState<DrawingRecord | null>(null);
  const [title, setTitle] = useState(''); const [caption, setCaption] = useState(''); const [guide, setGuide] = useState<DrawingGuide>('blank'); const [paths, setPaths] = useState<CanvasPath[]>([]);
  const [checklist, setChecklist] = useState<DrawingChecklist>(emptyChecklist); const [tool, setTool] = useState<'pen'|'eraser'>('pen'); const [color, setColor] = useState('#172554'); const [width, setWidth] = useState(4);
  const [score, setScore] = useState<ScoreSummary | null>(null); const [mark, setMark] = useState<ReviewerMark | null>(null); const [reviewerMode, setReviewerMode] = useState(false);
  const [rubric, setRubric] = useState({ relationship: 0, flow: 0, condition: 0, edgeCase: 0 }); const [feedback, setFeedback] = useState('');
  const [busy, setBusy] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [dirty, setDirty] = useState(false);
  const completed = drawing?.status === 'completed';
  const refreshScore = useCallback(async () => { try { const data = await api<{ score: ScoreSummary }>(`${endpoint}/score?version=${version}`); setScore(data.score); setMark(data.score.reviewerMark); } catch (e) { setError((e as Error).message); } }, [endpoint, version]);
  const load = useCallback(async () => { setError(''); try { const data = await api<{ drawing: DrawingRecord|null; previousDrawing: DrawingRecord|null; checklist: { checklist: DrawingChecklist }|null; reviewerMark: ReviewerMark|null; reviewerMode: boolean }>(`${endpoint}/drawing?version=${version}`); setDrawing(data.drawing); setPrevious(data.previousDrawing); setReviewerMode(data.reviewerMode); setMark(data.reviewerMark); const record = data.drawing; setTitle(record?.title ?? ''); setCaption(record?.caption ?? ''); setGuide(record?.guide ?? 'blank'); setChecklist(data.checklist?.checklist ?? emptyChecklist); setPaths(record?.paths ?? []); setDirty(false); setTimeout(() => { canvas.current?.resetCanvas(); if (record?.paths.length) canvas.current?.loadPaths(record.paths); }, 0); } catch (e) { setError((e as Error).message); } }, [endpoint, version]);
  useEffect(() => { void load(); void refreshScore(); }, [load, refreshScore]);
  useEffect(() => { void refreshScore(); }, [achievementTick, quizPassed, refreshScore]);
  useEffect(() => { if (!dirty) return; const guard = (event: BeforeUnloadEvent) => { event.preventDefault(); event.returnValue = ''; }; window.addEventListener('beforeunload', guard); return () => window.removeEventListener('beforeunload', guard); }, [dirty]);
  async function payloadPaths() { return canvas.current?.exportPaths() ?? paths; }
  async function saveDraft() { setBusy('save'); setError(''); try { const data = await api<{ drawing: DrawingRecord }>(`${endpoint}/drawing`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ version, revision: drawing?.revision ?? 0, title, caption, guide, paths: await payloadPaths() }) }); setDrawing(data.drawing); setDirty(false); setMessage('Draft saved and can be restored later.'); } catch (e) { setError((e as Error).message); setMessage('Save failed. Your unsaved drawing remains in this browser.'); } finally { setBusy(''); } }
  async function complete() { if (!canvas.current) return; setBusy('complete'); setError(''); completionKey.current ??= crypto.randomUUID(); try { const data = await api<{ drawing: DrawingRecord; achievements?: { awardedEvents?: string[]; awardedBadges?: string[] } }>(`${endpoint}/drawing/complete`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ version, revision: drawing?.revision ?? 0, title, caption, guide, paths: await payloadPaths(), checklist, previewDataUrl: await canvas.current.exportImage('png', { width: 900, height: 520 }), idempotencyKey: completionKey.current }) }); setDrawing(data.drawing); completionKey.current = null; setDirty(false); setMessage('Drawing completed. This is an activity record, not proof of understanding.'); if (data.achievements?.awardedEvents?.length || data.achievements?.awardedBadges?.length) celebrate(); await refreshScore(); } catch (e) { const saved = (e as { details?: DrawingRecord }).details; if (saved?.id && saved.reviewVersion === version) setDrawing(saved); setError((e as Error).message); setMessage('Completion failed. Your editable drawing remains available; retry after resolving the error.'); } finally { setBusy(''); } }
  async function download() { if (!canvas.current) return; const anchor = document.createElement('a'); anchor.href = await canvas.current.exportImage('png', { width: 900, height: 520 }); anchor.download = `${title.trim().replace(/[^a-z0-9]+/gi, '-').toLowerCase() || 'solution-drawing'}.png`; anchor.click(); }
  function selectTool(next: 'pen'|'eraser') { setTool(next); canvas.current?.eraseMode(next === 'eraser'); }
  function copyPrevious() { if (!previous) return; setDrawing(null); setTitle(previous.title); setCaption(previous.caption); setGuide(previous.guide); setChecklist(emptyChecklist); setPaths(previous.paths); canvas.current?.resetCanvas(); canvas.current?.loadPaths(previous.paths); setDirty(true); setMessage('Copied the previous drawing into a new draft. Review and update it for this code version.'); }
  async function saveMark() { if (!drawing) return; setBusy('mark'); setError(''); reviewerKey.current ??= crypto.randomUUID(); try { const data = await api<{ reviewerMark: ReviewerMark }>(`${endpoint}/reviewer-mark`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ version, drawingId: drawing.id, criteria: rubric, feedback, idempotencyKey: reviewerKey.current }) }); setMark(data.reviewerMark); reviewerKey.current = null; setMessage('Reviewer rubric saved separately from learning points.'); await refreshScore(); } catch (e) { setError((e as Error).message); } finally { setBusy(''); } }
  const completionReady = quizPassed && !!title.trim() && nonWhitespaceLength(caption) >= DRAWING_CAPTION_MIN && paths.some(path => path.drawMode && path.paths.length) && Object.values(checklist).every(Boolean);
  return <div className="phase4-area">
    <section className="drawing-section" aria-labelledby="drawing-title"><div className="phase4-heading"><div><span className="eyebrow">PHASE 04 · DRAW & REWARD</span><h2 id="drawing-title">Draw the solution</h2><p>Show the starting event, an important decision, the result, and one error or edge-case path.</p></div><span className={completed ? 'drawing-status complete' : 'drawing-status'}>{completed ? 'Completed' : quizPassed ? 'Ready to draw' : 'Preview locked'}</span></div>
      <p className="drawing-policy">This learning activity records completion only. It does not prove that the drawing or the learner’s understanding is correct. Drawing is optional for merge and earns bonus points.</p>
      {!quizPassed && <div className="review-notice">Pass the quiz for review {version.slice(0, 10)} to draw, save, and earn completion points.</div>}{previous && !drawing && <div className="stale-drawing"><strong>Earlier drawing is outdated for this review.</strong><span>It remains preserved under version {previous.reviewVersion.slice(0, 10)}.</span><button disabled={!quizPassed} onClick={copyPrevious}>Copy into this version</button></div>}
      {error && <div className="error" role="alert">{error}</div>}
      <div className="drawing-fields"><label>Drawing title<input required maxLength={DRAWING_TITLE_MAX} disabled={!quizPassed || completed || !!busy} value={title} onChange={event => { setTitle(event.target.value); setDirty(true); }}/></label><label>Background guide<select disabled={!quizPassed || completed || !!busy} value={guide} onChange={event => { setGuide(event.target.value as DrawingGuide); setDirty(true); }}>{Object.entries(guideLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></div>
      <div className="drawing-toolbar" role="toolbar" aria-label="Drawing tools"><button aria-label="Pen tool" aria-pressed={tool === 'pen'} disabled={!quizPassed || completed} onClick={() => selectTool('pen')}><Pencil size={16}/> Pen</button><button aria-label="Eraser tool" aria-pressed={tool === 'eraser'} disabled={!quizPassed || completed} onClick={() => selectTool('eraser')}><Eraser size={16}/> Eraser</button><button aria-label="Undo last drawing action" disabled={!quizPassed || completed} onClick={() => canvas.current?.undo()}><Undo2 size={16}/> Undo</button><button aria-label="Redo drawing action" disabled={!quizPassed || completed} onClick={() => canvas.current?.redo()}><Redo2 size={16}/> Redo</button><button aria-label="Clear drawing canvas" disabled={!quizPassed || completed} onClick={() => canvas.current?.clearCanvas()}><Trash2 size={16}/> Clear</button><label className="color-control">Stroke color<input aria-label="Stroke color" type="color" value={color} disabled={!quizPassed || completed} onChange={event => setColor(event.target.value)}/></label><label className="width-control">Stroke width<select aria-label="Stroke width" value={width} disabled={!quizPassed || completed} onChange={event => setWidth(Number(event.target.value))}><option value="2">Thin</option><option value="4">Medium</option><option value="8">Thick</option></select></label></div>
      <div className={`canvas-wrap ${!quizPassed || completed ? 'canvas-disabled' : ''}`} aria-label="Solution drawing canvas. Pointer and touch drawing surface."><ReactSketchCanvas ref={canvas} width="100%" height="420px" canvasColor="#fffdf8" backgroundImage={guideImage(guide)} exportWithBackgroundImage strokeColor={color} strokeWidth={width} eraserWidth={18} allowOnlyPointerType="all" onChange={updated => { setPaths(updated); if (quizPassed && !completed) setDirty(true); }}/></div><div className="tool-state" role="status" aria-live="polite">Current tool: {tool}. Freehand drawing needs a pointer or touch device; use the caption and checklist to describe the same concept without drawing.</div>
      <label className="caption-field">What does your drawing show?<textarea required maxLength={DRAWING_CAPTION_MAX} disabled={!quizPassed || completed || !!busy} value={caption} onChange={event => { setCaption(event.target.value); setDirty(true); }}/><small>{nonWhitespaceLength(caption)} / {DRAWING_CAPTION_MIN} non-whitespace characters minimum</small></label>
      <fieldset className="drawing-checklist" disabled={!quizPassed || completed || !!busy}><legend>Learner completion checklist</legend>{([['input','My drawing shows the input or starting point.'],['condition','My drawing shows a condition or decision.'],['result','My drawing shows the result or output.'],['edgeCase','My drawing includes an error or edge-case path.']] as const).map(([key, label]) => <label key={key}><input type="checkbox" checked={checklist[key]} onChange={event => { setChecklist({ ...checklist, [key]: event.target.checked }); setDirty(true); }}/>{label}</label>)}<p>Self-reporting these items records completion; it does not verify semantic correctness.</p></fieldset>
      <div className="drawing-actions"><button disabled={!quizPassed || completed || !!busy} onClick={saveDraft}><Save size={16}/>{busy === 'save' ? 'Saving…' : 'Save draft'}</button><button disabled={!quizPassed || completed || !!busy || !completionReady} className="primary-review" onClick={complete}><Sparkles size={16}/>{busy === 'complete' ? 'Saving preview…' : 'Mark drawing complete'}</button><button disabled={!paths.length} onClick={download}><Download size={16}/>Export PNG</button>{drawing && <button onClick={load}><RotateCcw size={16}/>Restore saved drawing</button>}<span role="status" aria-live="polite">{message}</span></div>{completed && <img className="drawing-preview" src={`${endpoint}/drawing/preview?version=${version}`} alt={`Exported preview of ${drawing.title}`}/>}</section>
    <section className="score-section" aria-labelledby="score-title"><div className="score-total"><div><span className="eyebrow">CURRENT REVIEW · {version.slice(0, 10)} · UP TO DATE</span><h2 id="score-title">Learning score: {score?.total ?? '—'}/100</h2><p>{score?.remaining ?? '—'} points still available. Reviewer marks are separate.</p></div><Award size={34}/></div><div className="score-grid">{score?.activities.map(activity => <div key={activity.event}><span>{activity.label}</span><strong>{activity.earned}/{activity.available}</strong></div>)}</div><div className="score-separate"><span>Drawing completion: <strong>{score?.drawingCompletion.earned ?? 0}/10</strong></span><span>Reviewer mark: <strong>{mark ? `${mark.total}/20` : 'Not marked'}</strong></span></div><div className="badges"><h3>Badges</h3>{badgeKeys.map(key => { const earned = score?.badges.some(item => item.badge === key); return <span key={key} className={earned ? 'earned' : 'locked'}>{earned ? 'Earned' : 'Locked'} · {badgeLabels[key]}</span>; })}</div></section>
    <section className="reviewer-section" aria-labelledby="reviewer-title"><h2 id="reviewer-title">Optional reviewer rubric</h2><p>{reviewerMode ? 'Local demo reviewer mode is enabled. Marks are stored separately and never converted to points.' : 'Reviewer mode is disabled by default. A server operator may explicitly enable local demo reviewer mode.'}</p>{mark && <div className="review-notice">Current reviewer mark: {mark.total}/20{mark.feedback ? ` — ${mark.feedback}` : ''}</div>}{reviewerMode && completed && <>{Object.entries(rubricLabels).map(([key, label]) => <label className="rubric-row" key={key}><span>{label}</span><select value={rubric[key as keyof typeof rubric]} onChange={event => setRubric({ ...rubric, [key]: Number(event.target.value) })}>{[0,1,2,3,4,5].map(value => <option key={value}>{value}</option>)}</select><small>/5</small></label>)}<label className="caption-field">Optional reviewer feedback<textarea maxLength={3000} value={feedback} onChange={event => setFeedback(event.target.value)}/></label><button className="primary-review" disabled={busy === 'mark'} onClick={saveMark}>{busy === 'mark' ? 'Saving mark…' : 'Save reviewer mark'}</button></>}</section>
  </div>;
}
