'use client';
import { useEffect, useState } from 'react';
import dynamic from 'next/dynamic';
import { answerKeys, explanationComplete, EXPLANATION_MIN, EXPLANATION_MAX, nonWhitespaceLength, type AgentRecord, type Answers, type ReviewSnapshot, type ReviewContent, type ExplanationRecord } from '@classroom/shared';
import { backendFetch } from '../lib/backend-fetch';
const DiffViewer = dynamic(() => import('react-diff-viewer-continued'), { ssr: false, loading: () => <p>Loading diff viewer…</p> });
const QuizMerge = dynamic(() => import('./quiz-merge'), { ssr: false });
const empty: Answers = { problem: '', solution: '', edgeCase: '' };
const labels = { problem: 'What problem does this change solve?', solution: 'How does the solution work?', edgeCase: 'What edge case or failure should be tested?' };
const hints = { problem: 'Describe the original behavior and why it needed to change.', solution: 'Describe the condition that changed and what happens when it is true.', edgeCase: 'Name an unusual input or failure and the result you would expect.' };
export default function Review({ agent, backend, onClose }: { agent: AgentRecord; backend: string; onClose: () => void }) {
  const [review, setReview] = useState<ReviewSnapshot | null>(null);
  const [selected, setSelected] = useState(''); const [content, setContent] = useState<ReviewContent | null>(null);
  const [answers, setAnswers] = useState<Answers>(empty); const [dirty, setDirty] = useState(false);
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [fileError, setFileError] = useState('');
  const [message, setMessage] = useState(''); const [pasteMessage, setPasteMessage] = useState('');
  const [split, setSplit] = useState(true);
  const endpoint = `${backend}/api/agents/${agent.id}`;
  async function request<T>(route: string, init?: RequestInit): Promise<T> { const response = await backendFetch(endpoint + route, init); const data = await response.json(); if (!response.ok) throw Object.assign(new Error(data.error || 'Request failed.'), { status: response.status }); return data; }
  useEffect(() => { const narrow = window.matchMedia('(max-width: 800px)'); const change = () => setSplit(!narrow.matches); change(); narrow.addEventListener('change', change); return () => narrow.removeEventListener('change', change); }, []);
  useEffect(() => { let cancelled = false; setBusy(true); request<ReviewSnapshot>('/review').then(data => { if (cancelled) return; setReview(data); setSelected(data.files[0]?.id ?? ''); setAnswers(data.explanation?.answers ?? data.previousExplanation?.answers ?? empty); setMessage(data.explanation?.status === 'completed' ? 'Explanation completed' : data.explanation ? 'Saved draft restored' : data.previousExplanation ? 'Earlier writing restored. Review this version and save it again.' : ''); }).catch(e => { if (!cancelled) setError(e.message); }).finally(() => { if (!cancelled) setBusy(false); }); return () => { cancelled = true; }; }, [endpoint]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { if (!dirty) return; const guard = (event: BeforeUnloadEvent) => { event.preventDefault(); event.returnValue = ''; }; window.addEventListener('beforeunload', guard); return () => window.removeEventListener('beforeunload', guard); }, [dirty]);
  useEffect(() => { let cancelled = false; setContent(null); setFileError(''); const file = review?.files.find(f => f.id === selected); if (review && file && !file.unsupported && !file.limited) request<ReviewContent>(`/review/files/${selected}?version=${review.version}`).then(data => { if (!cancelled) setContent(data); }).catch(e => { if (!cancelled) setFileError(e.message); }); return () => { cancelled = true; }; }, [selected, review?.version, endpoint]); // eslint-disable-line react-hooks/exhaustive-deps
  async function refresh() { setBusy(true); setError(''); try { const next = await request<ReviewSnapshot>('/review/refresh', { method: 'POST' }); const changed = next.version !== review?.version; setReview(next); setSelected(id => next.files.some(f => f.id === id) ? id : next.files[0]?.id ?? ''); if (changed) { setDirty(true); setMessage('Changes updated. This version needs its own completion; your writing stays here. Inspect the new diff before completing again.'); } else setMessage('Changes are up to date. Your writing is preserved.'); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function save(intent: 'draft' | 'complete') { if (!review) return; setBusy(true); setError(''); setMessage('Saving…'); try { const data = await request<{ explanation: ExplanationRecord }>('/explanation', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ version: review.version, answers, intent }) }); setReview({ ...review, explanation: data.explanation, outdated: false }); setDirty(false); setMessage(intent === 'complete' ? 'Explanation completed' : 'Draft saved'); } catch (e) { setError((e as Error).message); setMessage('Save failed. Your writing is preserved.'); if ((e as { status?: number }).status === 409) { setDirty(true); setReview({ ...review, explanation: null, outdated: true }); } } finally { setBusy(false); } }
  const file = review?.files.find(f => f.id === selected);
  const completed = !dirty && review?.explanation?.status === 'completed';
  return <section className="review-panel panel" aria-label="Review and explain"><div className="review-heading"><div><div className="eyebrow">PHASE 02 · REVIEW & EXPLAIN</div><h2>{agent.name} · Review changes</h2><p>{agent.task}</p></div><button onClick={() => { if (!dirty || window.confirm('Leave this review with unsaved writing? Save a draft to preserve it.')) onClose(); }}>Back to classroom</button></div><p className="review-base">Base branch <strong>{agent.baseBranch}</strong> · Starting commit <code>{agent.startCommit}</code></p><p className="review-terminal-note">The live terminal remains accessible above. Process status: <strong>{agent.status}</strong>.</p>
    {error && <div className="error" role="alert">{error}</div>}<div className="review-actions"><button onClick={refresh} disabled={busy}>Refresh changes</button>{review && <><span>{review.files.length} changed {review.files.length === 1 ? 'file' : 'files'}</span><span className="additions">+{review.additions}</span><span className="deletions">−{review.deletions}</span><span className="review-version" title={review.version}>Version {review.version.slice(0, 10)}</span></>}</div>
    {busy && !review && <p role="status">Collecting a stable review snapshot…</p>}{review && <>{review.outdated && <div className="review-notice">Earlier explanation is outdated. Its writing is preserved; this version needs its own completion.</div>}{!review.canComplete && <div className="review-notice">{review.files.length ? 'Some changes cannot be fully displayed. Totals cover supported text only. You may save a draft; completion is disabled.' : 'No changes found against the recorded starting commit. There is nothing to complete.'}</div>}
    {!!review.files.length && <div className="review-workspace"><nav className="review-files" aria-label="Changed files">{review.files.map(item => <button key={item.id} className={selected === item.id ? 'chosen-file' : ''} onClick={() => setSelected(item.id)}><span>{item.previousPath ? `${item.previousPath} → ` : ''}{item.path}</span><small>{item.status} {item.unsupported || item.limited ? '· unavailable' : `· +${item.additions} −${item.deletions}`}</small></button>)}</nav><div className="review-diff"><div className="diff-toolbar"><strong>{file?.path}</strong><div role="group" aria-label="Diff layout"><button aria-pressed={split} onClick={() => setSplit(true)}>Split</button><button aria-pressed={!split} onClick={() => setSplit(false)}>Inline</button></div></div><div className="diff-labels">Before: recorded base commit → After: review snapshot</div>{file && <div className="diff-modes">File mode: {file.oldMode} → {file.newMode}</div>}{file?.reason ? <p className="review-notice">{file.reason}</p> : fileError ? <p role="alert" className="error">{fileError}</p> : content ? <div className="diff-scroll"><DiffViewer oldValue={content.before} newValue={content.after} splitView={split} leftTitle={split ? 'Before · base commit' : 'Before (−) / After (+)'} rightTitle="After · review snapshot" showDiffOnly={false} disableWordDiff disableWorker hideSummary styles={{ contentText: { fontSize: '12px', lineHeight: '1.7' } }}/>{content.before === content.after && <p className="diff-labels">Text is unchanged. Review the path and file-mode changes above.</p>}</div> : <p role="status">Loading file from this review version…</p>}</div></div>}
    <form className="explanation-form" onSubmit={event => { event.preventDefault(); void save('complete'); }}><div className="explanation-title"><div><h2>Explain it in your own words</h2><p>Connect the code change to the problem it solves.</p></div><span className={completed ? 'explanation-badge complete' : 'explanation-badge'}>{completed ? 'Explanation completed' : dirty ? 'Unsaved writing' : review.explanation ? 'Draft' : 'Not completed'}</span></div><p className="explanation-policy">This is a learning exercise. Paste and text drop are disabled only here. Length checks establish completeness, not correctness or understanding.</p><div aria-live="polite" role="status" className="paste-message">{pasteMessage}</div>{answerKeys.map((key, index) => <div className="answer-field" key={key}><label htmlFor={`answer-${key}`}>{index + 1}. {labels[key]}</label><p id={`hint-${key}`}>{hints[key]}</p><textarea id={`answer-${key}`} aria-describedby={`hint-${key} progress-${key}`} required maxLength={EXPLANATION_MAX} value={answers[key]} disabled={busy} onChange={event => { setAnswers({ ...answers, [key]: event.target.value }); setDirty(true); setMessage(''); }} onPaste={event => { event.preventDefault(); setPasteMessage('Write this explanation in your own words. Pasting is disabled in this activity.'); }} onDragOver={event => event.preventDefault()} onDrop={event => { event.preventDefault(); setPasteMessage('Write this explanation in your own words. Pasting is disabled in this activity.'); }}/><small id={`progress-${key}`}>{nonWhitespaceLength(answers[key])} / {EXPLANATION_MIN} non-whitespace characters minimum · {EXPLANATION_MAX} maximum characters</small></div>)}<div className="explanation-save"><button type="button" onClick={() => save('draft')} disabled={busy}>Save draft</button><button className="primary-review" type="submit" disabled={busy || !review.canComplete || !explanationComplete(answers)}>Mark explanation complete</button><span role="status" aria-live="polite">{message}</span></div></form><QuizMerge agent={agent} backend={backend} version={review.version} explanationCompleted={completed}/></>}
  </section>;
}
